title: "Ayushi Srivastava"
email: ayushimanoj1201@gmai.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://srivastavayushi.github.io/" 
twitter_username: AyushiS38583735
github_username:  srivastavayushi

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
